name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Run install
        run: npm install
      - name: Run Jest coverage
        run: npm run test:coverage &
      - name: Build storybook
        run: npm run build-storybook
      - name: Serve storybook
        run: nohup npx http-server -p 6006 storybook-static &
      - name: Run Cypress coverage
        run: npm run cypress:run
      - name: Run Coverage merge
        run: npx wait-on http://127.0.0.1:6006 && npm run coverage:merge
      - name: Run codecov
        run: npx codecov --token=${{ secrets.CODECOV_TOKEN }} --file=coverage.json
